version: "3"
services:
  qnode:
    build:
      context: .
      dockerfile: DockerfileQnode
    container_name: qnode
    restart: unless-stopped
    volumes:
      - ./mainnetdb:/app/mainnetdb:rw
    ports:
      - "14666:14666/tcp"
      - "14626:14626/udp"
      - "14626:14626/tcp"
      - "8080:8080/tcp"
