name: Test GoShimmer Plugin Qnode
on:
  push:
  pull_request:
    branches: [ dev ]
jobs:

  build:
    name: Test GoShimmer Plugin Qnode
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Tests
      run: go test ./plugins/qnode/...
